### ISSUE TITLE
add support for extracting only certain channels

### ISSUE THREAD

**Issue by eackermann** [eackermann/nelpy#126]
not sure of final interface, but for now, should mimic SpikeTrainArray._unit_subset, so maybe AnalogSignalArray._subset should be fine.

Note, this should also propagate channel / signal information.

For example, we may have a position analog signal with (x,y,z) channels, and if we cut out (y,z), the labels should propagate. Similarly, if we start with all channels recorded from tetrodes, and we cut out channel 3 with AnalogSignalArray._subset[[3,11,16]] then those channel names should be propagated to the new object. 

This has already been implemented in SpikeTrainArray, so you can try it out for inspiration. One note of caution: I mad the units start at 1 (yeah, you mad! who does 1 indexing?), and not at 0. Unit 0 is reserved (although not exclusively) for unsorted spikes. In an AnalogSignalArray, I guess _subset[[0,1,2]] should return the first three signals / channels.

**Comment by eackermann** [comment]
I currently need this, because I want to plot LFP above my spiking activity (like most of the replay figures we always see). But my AnalogSignalArray has multiple signals in it, and I actually only want to plot one of them as the designated LFP channel

**Comment by shayokdutta** [comment]
Done for now...further issue written on board :)
