### ISSUE TITLE
Add AnalogSignalArray.lengths

### ISSUE THREAD

**Issue by eackermann** [eackermann/nelpy#134]
Should return the length (in # samples) of each segment in the signal array.

**Comment by shayokdutta** [comment]
well......this is interesting.....

Right now, we would just have asa.ydata.shape[0] but that won't work in the future for jagged ASAs. With that in mind though, I think it'd be best to return a N-dimensional array of # samples. Would you agree?

**Comment by eackermann** [comment]
No!

**Comment by shayokdutta** [comment]
:open_mouth: :no_good_man:

**Comment by eackermann** [comment]
LOL! See? That's why we have an issues list. I clearly wanted this loooong ago.
