### ISSUE TITLE
Comparison to None might lead to unexpected behavior in AnalogSignalArray

### ISSUE THREAD

**Issue by eackermann** [eackermann/nelpy#137]
We have a futurewarning that `if(self._ydata[indices,:] != None)` will be element-wise in the future.

@shayokdutta what exactly did you want this to do? If _ydata exists, then maybe it will return an IndexError (but not equal to None), or it might be an empty array (but again, probably won't equal to None),... it's used in a number of cases and places, but should probably be revised to make the intended meaning clear, or to make it so that it won't break in a future release of numpy.

**Comment by eackermann** [comment]
Can you maybe look into this soon?

**Comment by shayokdutta** [comment]
by numpy you mean nelpy right? now that we've switched from columns to rows to contain each signal, i no longer think this is an issue

**Comment by shayokdutta** [comment]
``` python
emptyASA = AnalogSignalArray([],empty=True)
emptyASA[0]
`
returns attribute error

**Comment by eackermann** [comment]
@shayokdutta no, I meant future release of numpy.

I kept getting an warning about comparing to None, saying it will become an error in a future release of numpy

**Comment by shayokdutta** [comment]
The logic for this can simply be changed to 
`len(self._ydata[:,indices])>0`

but you are right this is useless it should just be wrapped in a try and except Index error block. 
This is now done and the error I raised above is also handled. Both modifications have been pushed.
