### ISSUE TITLE
AnalogSignalArray initialization incorrect with step and fs

### ISSUE THREAD

**Issue by eackermann** [eackermann/nelpy#141]
mua1 = nel.AnalogSignalArray(smoothed_spikes1, tdata=mua_binned1.centers, step=0.001, fs=1/mua_binned1.ds)

**Comment by eackermann** [comment]
smothed_spikes1 has 1000 samples/sec. If fs=None, it works, but it complains that fs is not set, and I actually need it later. If fs=1000 is passed, then it doesn't return the correct underlying support.

**Comment by shayokdutta** [comment]
I believe this has now been resolved
