### ISSUE TITLE
implement n_active for SpikeTrainArrays

### ISSUE THREAD

**Issue by eackermann** [eackermann/nelpy#142]
My current plan is to make them behave similar to mean() etc. from AnalogSignalArray. That is, n_active should apply to the entire raster in the spiketrain, and spit out a scalar value.

However, if we then want the n_active for events (segments), it's a simple matter to use a list comprehension: `[event.n_active for event in spiketrain]`

BUT! This may be confusing when compared to the behavior of `.n_active` in `BinnedSpikeTrainArray`, where by default it applies column-wise, that is, per time bin, and not per event, nor across the entire raster.

How can we rename this more intuitively?

**Comment by jchutrue** [comment]
I'm not sure I understand completely what the issue is. It looks like you're hunting for the number of units active during a certain event, is that correct? If so, what about `.n_active_per_event`?

**Comment by eackermann** [comment]
The issue is consistency.

In AnalogSignalArray, we can have, say, 5 segments (5 disjoint support epochs), and yet if we do
`analogsignalarray.mean()` we obtain the mean of the _entire_ signal. That is, we get a scalar value out. If, on the other hand, we wanted to get the means of every segment, the pythonic way to write that would be
`means = [segment.mean() for segment in analogsignalarray]`, i.e., a list comprehension.

This works nicely, and reads easily. It is clear what to expect in each case by just looking at the code.

**Comment by eackermann** [comment]
Similarly, I want a `spiketrainarray.n_active` property, which should operate on the entire raster, and if we want to have the number of active cells within each segment, we can do a list comprehension just as above.

The difficulty came in when we have a `BinnedSpikeTrainArray`, for which it is natural to want to know how many cells were active _per time bin_, which is roughly equal then, to the mua firing rate. For example, 5 cells in bin 1, 4 cells in bin 2, only 2 cells in bin 3, and so on. This functionality already exists, and is called `binnedspiketrain.n_active`. This is a common criterion for looking at replay, for example, where we require >= 5 place cells to be active, etc.

So I am wondering if I should change `BinnedSpikeTrain.n_active` to mimic the proposed behavior for SpikeTrainArray? And if so, what should I rename the per-bin variant? I could go with your suggestion of making a `.n_active_per_event`, but that would not be consistent with AnalogSignalArray, and I like the list comprehension solution a little better.

Also also, it is currently `analogsignalarray.mean()` to be similar to the `numpy` interface, but it is `spiketrainarray.n_active` to be more similar to other "properties" in nelpy, which are also used in `numpy`, such as `array.shape` and not `array.shape()`.

Hence this discussion is about _consistency_, _readability_, and API choices that we should probably stick to once we make a decision, because these will be publicly-facing.

**Comment by jchutrue** [comment]
Let's say `.n_active` were a variable that is defined over the entire raster. You could use a list comprehension to get all the `.n_active`'s for each segment. A segment is general enough where it could refer to a time bin, an event, or something else.

**Comment by eackermann** [comment]
Yes that is true, but I don't have a nice recipe for getting the `n_active` per time bin yet.

**Comment by eackermann** [comment]
So, it's been implemented by now, by the way, and we can do

`st.n_active  # total number of cells that fired at least 1 spike`

or 

`[segment.n_active for segment in st]  # the number of cells _per segment_ that fired at least 1 spike`

but I don't have a nice recipe for doing the _per-bin_ thing yet:

`st.bin().n_active  # currently returns an array of len(time_bins)`

but since this last one is the special case, maybe I should just have an explicit (and different) function call for this particular case. `binned.n_active_per_bin` is certainly descriptive enough, so I will do that for now I think, right?

**Comment by jchutrue** [comment]
I don't see any reason why you can't have `n_active_per_bin` for clarity's sake. What do you mean by recipe?

**Comment by eackermann** [comment]
By recipe, I meant the "preferred way" to write something.

Just like you _could_ get the `n_active` for each segment by writing
```
n_actives = []
for ii in range(st.n_epochs):
    segment = st[ii]
    n_actives.append(segment.n_active)
```

which will work, but it's not easy to read, nor pythonic.

So the _recipe_ would be

```
n_actives = [segment.n_active for segment in st]```

**Comment by eackermann** [comment]
Anyway, thanks for the discussion, @jchutrue ! This has now been implemented.
