### ISSUE TITLE
improve millisecond readability of PrettyTime

### ISSUE THREAD

**Issue by eackermann** [eackermann/nelpy#150]
Currently `PrettyDuration(62.3))` prints `1:02.300 minutes`, but it might be nice to have it print in fractions instead? E.g., `9.5 seconds` instead of `9:500 seconds`, but in the above case, should it be `1:02.3 minutes`? It could be confusing, then, since the `.3` refers to 300 ms or 0.3 seconds, and NOT 0.3 minutes.

**Comment by eackermann** [comment]
I think perhaps whenever we have > seconds, we should use
`hh:mm:ss:s` (+ string to identify largest nonzero unit, e.g. minutes)
whereas if we have seconds, we should use
`ss.s seconds`,
and if we only have milliseconds, we should use
`s milliseconds`

E.g.

`43:06:300 minutes`
`43:06 minutes`
`43:00 minutes` NOT `43 minutes` ==> or should we use the latter?
`18.4 seconds` NOT `18.400 seconds`
`340 milliseconds`
`27 milliseconds` NOT `027 milliseconds`

**Comment by jchutrue** [comment]
Very good, I like that idea
