### ISSUE TITLE
npl.epochplot() renders strangely in matplotlib 2.0 

### ISSUE THREAD

**Issue by eackermann** [eackermann/nelpy#152]
On matplotlib 1.5+ we get the following epoch plot

![image](https://cloud.githubusercontent.com/assets/8691267/24116337/79fc14c4-0d74-11e7-8f5f-cb534a3c0a8f.png)

**Comment by eackermann** [comment]
On matplotlib 2, we get this instead:

![image](https://cloud.githubusercontent.com/assets/8691267/24116580/44afd516-0d75-11e7-93f6-4aa8d374f40e.png)

**Comment by jchutrue** [comment]
What arguments did you pass in to epochplot()?

**Comment by eackermann** [comment]
This was a particular EpochArray, the one corresponding to mua events from gor01 in the hc3 dataset. The only characteristic was that the events were pretty short compared to the experiment duration, but I would still hope that they show up, as in the first figure

**Comment by eackermann** [comment]
Part of the issue might be how the new matplotlib handles 'none' parameters. This will need some careful investigation, which will be easiest if we can be side-by-side with two versions. I'm running matplotlib 2.0 on my lappy. I could start a virtual env, or I could just debug it with one of you guys who might still run matplotlib 1.5

**Comment by eackermann** [comment]
@jchutrue so I used default parameter values, and simply passed the same EpochArray in both instances.

**Comment by eackermann** [comment]
@jchutrue thanks for the fix! The newest version, using matplotib 2.0, now renders thus:

![image](https://cloud.githubusercontent.com/assets/8691267/24127562/8db2495a-0da3-11e7-8421-ed703b79760b.png)
