### ISSUE TITLE
PoissonHMM.__repr__ doesn't work

### ISSUE THREAD

**Issue by eackermann** [eackermann/nelpy#16]
I can't figure out how to access (or intercept) the `__repr__` from the parent class (hmmlearn.hmm.PoissonHmm)?

**Comment by eackermann** [comment]
Interestingly enough, this only happens on my tablet, which has an older set of packages installed. It has clearly been fixed since, but I am yet to figure out _which_ package caused this error, and which minimum version is required in order for this to work?

**Comment by eml5** [comment]
I git cloned the master branch.
import nelpy as nel

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-7013deac6e12> in <module>()
----> 1 import nelpy as nel

//anaconda/lib/python3.5/site-packages/nelpy/__init__.py in <module>()
     22                     find_nearest_indices)
     23 
---> 24 from .hmmutils import PoissonHMM
     25 
     26 # from .plotting import plot

//anaconda/lib/python3.5/site-packages/nelpy/hmmutils.py in <module>()
     13 
     14 # see https://github.com/ckemere/hmmlearn
---> 15 from hmmlearn.hmm import PoissonHMM as PHMM
     16 
     17 class PoissonHMM(PHMM):

ImportError: No module named 'hmmlearn'

**Comment by eackermann** [comment]
I am going to close this, as it seems like the minimum package specs we require to use nelpy do not have this error.
