### ISSUE TITLE
Need to squeeze numpy methods

### ISSUE THREAD

**Issue by eackermann** [eackermann/nelpy#162]
```python
def mean(self,*,axis=1):
        """Returns the mean of each signal in AnalogSignalArray."""
        try:
            return np.mean(self._ydata, axis=axis).squeeze()
        except IndexError:
            return np.mean(self._ydata)
```

Without the squeeze in the above, the list comprehensions become 2D arrays, which is unexpected. So we need to squeeze here, and also in std, min, max, and so on.

Also, what is the IndexError doing there? When will this ever happen?

**Comment by shayokdutta** [comment]
The index error won't happen anymore after changing from column data to row data. Has this been solved by you then?

**Comment by eackermann** [comment]
I did some squeezes, but the IndexErrors are still there as legacy code, so they should be cleaned up

Still, what if ydata doesn't exist? Or is this now impossible due to the new empty object format?

**Comment by shayokdutta** [comment]
I believe this will still be an error of some sort but that's expected? I mean if you try to calculate the mean of an empty ASA, I don't think there's a logical output.

**Comment by shayokdutta** [comment]
Errors are IndexErrors and ValueErrors they have been handled appropriately.
