### ISSUE TITLE
get_run_epochs uses tdata, might need to use time instead

### ISSUE THREAD

**Issue by eackermann** [eackermann/nelpy#204]
```
# convert bounds to time in seconds
RUN_bounds = speed.tdata[RUN_bounds]
```

@shayokdutta tdata should be time, right? In my current dataset, time \equiv tdata, but since I really want seconds, I should just stick with time...

**Comment by eackermann** [comment]
It has now been updated.

**Comment by shayokdutta** [comment]
I guess that works but I would have recommended using tdata and fs instead of time.

**Comment by shayokdutta** [comment]
because as you said, timestamps may be better as opposed to floating point representations of time depending on sampling rate.

**Comment by eackermann** [comment]
I used to believe this, but it gets modified so often, that I no longer think any particular (modified, downstream) object has any advantage of tdata over time. In this case, the decision to use time is for coding clarity. fs is superfluous, but is there to suppress the warning that would result otherwise.
