### ISSUE TITLE
subsample can generate NaNs

### ISSUE THREAD

**Issue by eackermann** [eackermann/nelpy#217]
This happens when points are requested outside of a signal's support, I believe

This should robustly be fixed in asarray

**Comment by shayokdutta** [comment]
My temporary solution
`asa._ydata = np.delete(asa.ydata, np.where(np.isnan(asa._ydata))[1], 1)`

**Comment by eackermann** [comment]
can you confirm that these points happened outside of the original support?

**Comment by shayokdutta** [comment]
On the examples I've run, yes.

**Comment by eackermann** [comment]
Then see issue #160

**Comment by eackermann** [comment]
(although I have to think more carefully why simplify will ever lead to that behavior...)

**Comment by eackermann** [comment]
Fixed!
