### ISSUE TITLE
Extend AnalogSignal class

### ISSUE THREAD

**Issue by eackermann** [eackermann/nelpy#23]
extend AnalogSignal to have an EpochArray support, and to support indexing, slicing, .mean(), .std(), .max(), .min(), .trim([from, to], .clip(min, max), and .smooth()

Questions: are all of these sensible for a generic AnalogSignal class, or are they more specialized to the LFP instantiation? How about the position class that Emily has created as a subclass of AnalogSignal, for example? Worth a second look, and thinking a little before we commit.

**Comment by eackermann** [comment]
@shayokdutta we should probably leave the smooth() function until we've thought things through a bit more, but also feel free to add additional functionality that I didn't list above

**Comment by shayokdutta** [comment]
I did text you this but just to keep a log I'll post it on here...

Why do we want to support mean, std, smooth, etc? Wouldn't returning ydata and enabling the user to do whatever he or she would like to do be the appropriate approach in this case? Or else you're going to have to keep having to add wrapper functionality from numpy or scipy or whatever for more things that I want to do (e.g. ripple band filter the signal)

**Comment by eackermann** [comment]
Because (1) I like the interface more, it's cleaner and more Pythonic, (2) keeping track of simple things can become painful otherwise, (3) the user can always access the underlying data if they need to, but we shouldn't design the code so that they have to, (4) many more reasons.

As a simple example, smooth should respect gaps in the data. If we simply return ydata (which does not have any information about xdata nor gaps) then how will the user smooth it easily? Something trivial suddenly becomes something complicated.

Also, instead of simply having the mean, std, smooth, etc. as class methods, they can also be nelpy general functions that understand the core nelpy objects. Much like you can do 

`np.mean(signal) and signal.mean()`

it would be nice if we can do

`nel.mean(analogsignal) or analogsignal.mean()`

As for filtering, I do not think it's advisable to have that be a class method. Even with numpy, we don't do signal.filter(params), but instead call some scipy function and pass the ndarray to that.

Similarly, nelpy now has a filtering submodule (perhaps a subpackage later), so that you would call

`nel.filtering.butter_filtfilt(analogsignal, **kwargs)`

or if you want a cleaner interface,
```
from nel.filtering import butter_filtfilt
butter_filtfilt(analogsignal, **kwargs)
```

This way we get to re-use the filtering methods for multiple objects, without having to add them to each object's class definition.

We can debate about which functions should be wrapped as class methods, and I'd always be guided by numpy, but it also comes down to usage. Taking the mean is a very frequently used diagnostic tool, and one which I want at my fingertips, like `signal.mean()` or `signal.sum()`, or `signal.n_samples` etc. whereas filtering is not so fundamental for me.

One important point: things like mean() should really be methods and not properties, so that you can pass the axis (default of zero, of course) just like in numpy, to (1) average across time, or (2) average across all channels in the AnalogSignalArray. This (making mean, std, etc. functions instead of properties) also makes the interface more familiar to people used to numpy.

**Comment by shayokdutta** [comment]
This is done for the most part...I mean there's always going to be enhancement requests but those can be opened with a new issue. As such, I'll close this and I like clicking close it looks like I've made progress.
