### ISSUE TITLE
Refactor to consolidate SpikeTrain and SpikeTrainArray, as well as AnalogSignal and Binned variants

### ISSUE THREAD

**Issue by eackermann** [eackermann/nelpy#35]

**Comment by eackermann** [comment]
This has now been done for SpikeTrain and SpikeTrainArray. BinnedSpikeTrainArray is almost done.

**Comment by eackermann** [comment]
This has now been completed for SpikeTrainArray. Currently working on BinnedSpikeTrainArray.

@shayokdutta will this be within your reach after #paper ?

**Comment by eackermann** [comment]
This has now been completed for BinnedSpikeTrainArray as well.

**Comment by shayokdutta** [comment]
To confirm here, we want AnalogSignalArray correct? Not a binned variant of that? I don't think the latter would make sense much for the generic case of using AnalogSignal unless I'm not understanding what it means to bin

**Comment by shayokdutta** [comment]
Done! Feel free to reopen this. I just really want to click close and I think it is "done".
