### ISSUE TITLE
Shall we assume sorted for SpikeTrains and EpochArrays?

### ISSUE THREAD

**Issue by eackermann** [eackermann/nelpy#4]
We currently do sort starting times in EpochArray, which doesn't necessarily make sense, but we do NOT sort in SpikeTrain, where it almost certainly DOES make sense.

**Comment by eackermann** [comment]
For SpikeTrainArray, at least, we now always check to see if it's sorted first, which takes O(N). Then, only if necessary, do we sort, which takes O(Nlog(N)).

It may be worth doing something similar for AnalogSignalArray (where time is expected to be sorted, but cannot be guaranteed), but for EpochArray it is still unclear, since the starts and stops can be impossible to sort simultaneously (with overlapping Epochs, for example)

**Comment by eackermann** [comment]
This happens in __init__ of course, and should never happen anywhere else, like when we take slices, or iterate over objects...

**Comment by shayokdutta** [comment]
Hmm...Hmm....I'll come give you my opinions in person once you're done talking to @sillyproject

**Comment by eackermann** [comment]
@shayokdutta so what are those opinions?

**Comment by eackermann** [comment]
Update: it is necessary to sort EpochArray.starts for the current merge() algorithm to work properly. We now sort (again, only if necessary) the starts in the `__init__` and we also have an internal `EpochArray._sort()` which operates in-place.

**Comment by eackermann** [comment]
So... I never got those opinions. But since this has _finally_ been resolved, I am closing this issue.
