### ISSUE TITLE
AnalogSignal support not calculated properly

### ISSUE THREAD

**Issue by eackermann** [eackermann/nelpy#40]
Currently, we have code of the form

```
if support is None:
    self.support = EpochArray(np.array([0, xdata[-1]]), fs=fs)
else:
    #restrict signal to only those within the support
```

but this is not the desired behavior. If no support is given to `AnalogSignal`, it should figure out which contiguous segments the signal is defined on by looking at `xdata`. If no `xdata `is given, AND no support is given, then the above is appropriate. If no `xdata `is given, but an explicit support is given, well, then we'll have to think very carefully about what that means, and if it should even be allowed / supported.

**Comment by shayokdutta** [comment]
This isn't done yet! I just pushed the code yesterday to the feature branch before I left.

**Comment by shayokdutta** [comment]
Finally looking into this...I agree with everything you said but do want to clarify/discuss something. How would you define contiguous? If we were to define epochs based on contiguous segments within xdata, I'd say that it'd have to be based on the sampling rate but should we consider cases where the sampling is not consistent? 

As I'm typing this out, I don't think this is much of an issue...user should be cognizant of this prior to making an AnalogSignal object but we may want to specify or note that constant sampling rate is assumed?

**Comment by eackermann** [comment]
Yes, that is why there was talk of having an "IrregularlySampledAnalogSignal" class.

If you specify a sampling rate, then you better hope the sampling rate is fixed! That does not mean that there won't be missing data, which is where the whole contiguous thing comes in.

**Comment by shayokdutta** [comment]
With regards to the latter part of what you said, it is confusing if no xdata is given but an explicit support is specified. However, you can calculate xdata based on the given support and sampling rate (which can be taken from the support). I think it is fine if we allow this but I would make it so that the user not only explicitly specifies the support but also includes the sampling rate...that would somewhat indicate the user knows what (s)he is doing (I think).

**Comment by eackermann** [comment]
Definitely a warning, and maybe pretty straightforward (but unlikely to be useful) behavior:

automatically generate x-data without gaps (since no x-data was given) using fs if available, otherwise assume None and use integral samples for x-data. (Reasonable enough up to here).

Then, since an `EpochArray` support was passed, view it as a restriction on the newly created x-data, so that

```
epocharray = EpochArray([[4,6], [8,15]], fs=5)
as = AnalogSignal(ydata, fs=5)
as[epocharray]
```

would be equivalent to

`as = AnalogSignal(ydata, fs=5, support=epocharray)
`
as a kind of a lazy-man's shortcut, which should go with a warning, and which should generally be discouraged.

**Comment by eackermann** [comment]
I would argue against inferring the fs of AnalogSignal from the passed in support, because this is not done anywhere else, and would be the exception rather than the rule.

As my above suggestion / example stands, the behavior would still make sense if DIFFERENT sampling rates are given for AnalogSignal and the support, or if no sampling rate is given for AnalogSignal, and also if no sampling rate is given for either AnalogSignal or support.

So I still don't think this is a very likely / useful use case, but let's try to at least make it logical, and consistent with the rest of nelpy's behavior.

**Comment by shayokdutta** [comment]
Hmmm....I don't like this. So, I did end up implementing what you just said already. However after implementing it, I changed my mind....I don't think it should be allowed at all. In the case that xdata is not specified and a support is specified , as the developer, you have to make an assumption that the data is contiguous regardless of if fs is specified and you have to make an assumption that your starting time is zero when the epoch array could have starting time that is well shifted away from zero. 

Also based on what you just said, I don't think it makes sense for the underlying support to be able to have a different sampling rate than the AnalogSignal. 

Side note: I now agree fully, even with my incorrect definition, that this is not trivial!

**Comment by shayokdutta** [comment]
I am going to implement this with the requirement that __xdata and fs must be specified if a support is specified.__ I think that makes the most logical sense. In any other case, I think it gets complicated and could lead to countless user bugs...

**Comment by eackermann** [comment]
Agreed. Even in my example above, I just can't see it being very useful.

So we agree that

ydata only is very useful
xdata and ydata is useful
xdata and ydata and fs is useful
xdata and ydata and fs and support is useful

Am I missing any useful and/or supported cases?

I'm happy with raising TypeErrors if the correct type/combination of input data is not given.

**Comment by shayokdutta** [comment]
I think you got them all. I think this issue can be closed now since I have all the conditionals (lmk if I'm missing something in the code below) we need. 

> 
        if xdata is not None and fs is not None:
            time = xdata / fs
        elif xdata is not None:
            time = xdata
        # The cases below should be handled based on if a support was given
        #elif fs is not None:
        #elif xdata is None: 
        #elif fs is None:

        # determine AnalogSignal support and resolve xdata/time if needed:
        if support is None and xdata is None:
            if fs is not None:
                time = np.arange(0,len(values),1) / fs
                self.support = EpochArray(np.array([0, time[-1]]), fs=fs)
            else:
                time = np.arange(0,len(values),1)
                self.support = EpochArray(np.array([0, time[-1]]))
        elif support is None and xdata is not None:
            self.support = EpochArray(np.array([0, time[-1]]))
        elif support is not None and xdata is not None and fs is not None:
            if support.fs == fs:
                #restrict signal to only those within the support
                self.support = support
                self._restrict_to_epoch_array()
            else:
                self._emptyAnalogSignal()
                raise TypeError("sampling rate mismatch between support and passed fs")
        else:
            self._emptyAnalogSignal()
            raise TypeError("fs and xdata must be passed if support is specified.")

**Comment by eackermann** [comment]
I still don't think this is quite correct / complete.

What about (ydata, xdata, fs)? where does that get handled? That is the case where we should detect contiguous segments for the support.

Also, if we simply get (ydata, xdata) don't you think we should raise a warning? Because the support might not be computed as the user intends, since we cannot find gaps in the support, due to not having fs?

**Comment by eackermann** [comment]
There are other cases that don't seem obvious to me as well. This might be a perfect opportunity to enumerate all of the cases (only 3 variables: support, xdata, fs, so not a difficult task) , and to describe each one and its intended behavior in the docstring. This will also make writing tests for this class easier, and help us to make sure we're thinking about this properly.

**Comment by shayokdutta** [comment]
I believe this is done correctly now and has been tested! Last note just for records: ydata and xdata must be specified in order to specify an EpochArray as the support. Additionally, fs doesn't need to equal EpochArray's fs due to potential use cases where the sampling rate of the EpochArray might be specified from a video as opposed to LFP data.
