### ISSUE TITLE
Cannot differentiate between single and multiple spike trains

### ISSUE THREAD

**Issue by eackermann** [eackermann/nelpy#46]
If we make a `SpikeTrain` object, we assume a single unit, whereas if we make a `SpikeTrainArray` object we assume multiple units. However, we may want to merge both into one class, namely `SpikeTrain` that can have multiple units.

Input validation becomes tricky though, since we support taking in lists, arrays, and generally any array-like object.

How can we (robustly) differentiate between `st1 = [[2,3,4],[3,4],[5,7,8]]` and `st2 = [3,6,8]` ? In both cases, `len(st) == 3` and doing things like `np.squeeze(st)` doesn't get us much further, since then

`st1.ndim == 1` and `st2.ndim == 1` and `st1.size = 3` and `st2.size == 3` and even `st1.shape == (3, )` and `st2.shape == (3, )`.

 @shayokdutta any ideas?

**Comment by shayokdutta** [comment]
quick and dirty solution: have a flag for number of units

**Comment by eackermann** [comment]
Not gonna happen! Lol

**Comment by eackermann** [comment]
Thanks, @shayokdutta after many tricky coding sessions, I've crafted a masterful solution.
