### ISSUE TITLE
Indexing EpochArray with EpochArray aka Intersection Indexing Not Working

### ISSUE THREAD

**Issue by shayokdutta** [eackermann/nelpy#54]
Tested with develop branch commit of last update to EpochArray

**Comment by eackermann** [comment]
It would be helpful to know if this is the case when both EpochArrays have fs=None (as the case you showed me), or if this fails more generally as well.

At any rate, this should get fixed soon, and is related to #51

**Comment by shayokdutta** [comment]
I can probably look at it tomorrow morning and fix as if needed. Too tired
ATM to test the cases you said.

**Comment by eackermann** [comment]
fixed, and tested when fs = fs != None, and when fs != fs != None, and when fs = fs = None

NOT working for when one fs = None, while the other is specified. Opening new issue for that case.
