### ISSUE TITLE
Implement plotting.tuning_curves() for place field and similar visualization

### ISSUE THREAD

**Issue by eackermann** [eackermann/nelpy#72]
This should follow raster() fairly closely in that it should plot all the traces of the given set of units.

You'll have to think a bit about what input you really want to support. But underlying that input, you should be able to plot [multiple] tuning curves as a function of a [shared] behavioral correlate.

In the case of place fields, the behavioral correlate is position, so you plot rate as a function of position. But the behavioral correlate could easily be something different (angle, elapsed time, etc.). If the behavioral correlate is time, then the tuning curve effectively becomes a PSTH.

I think nelpy.plotting should have helper functions for things like PSTHs, so that with a sensible input, it would _compute_ the PSTH, and then use tuning_curves() to plot it appropriately. This is pretty much how seaborn works, e.g., when you do distplot or kdeplot, it has helper functions to _compute_ those objects, and then uses some of the built-in plotting functions to assemble a nice figure.

@jchutrue can you show @sillyproject some of the ropes to help her get started? I assigned her to this task, because she is supposed to plot place fields in this week anyway according to her 599 schedule. Might as well integrate it with (or start it in) nelpy.

**Comment by sillyproject** [comment]
I do need some help getting started here.

**Comment by eackermann** [comment]
Hello, @sillyproject

**Comment by eackermann** [comment]
Hey!

**Comment by eackermann** [comment]
The idea was to have a generic tuning curve plot type, and although we are now closer to having one, we still don't have what I wanted. At least the tuning curves for place fields are now powerful and flexible (in 1D only, OTL).

However, I am going to go ahead and close this issue, since there are too many open issues, and nothing being done about them.
